### ISSUE TITLE
[Feature]: Archiverse implementation

### ISSUE THREAD

**Issue by CCIGAMES** [PretendoNetwork/juxtaposition#6] opened 2024-09-13 23:47 UTC
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What feature do you want to see added?

Moving/copying the content from the https://archiverse.app/ archive to Pretendo's miiverse

### Why do you want to have this feature?

Because it helps make it feel like Pretendo truly picks up where Nintendo left off, like it's a true restoration of Miiverse.

### Any other details to share? (OPTIONAL)

It does have a github, and in another Pretendo repo about Miiverse I made a feature request post there that went into more detail

**Comment by MatthewL246** [comment] 2024-09-20 03:10
Duplicate of https://github.com/PretendoNetwork/miiverse-api/issues/43

**Closed by MatthewL246** 2024-09-20 03:10 UTC
Labels: awaiting-approval, feature
